// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: trade_dao.proto

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TradeDao struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Side          string                 `protobuf:"bytes,2,opt,name=side,proto3" json:"side,omitempty"`
	Id            string                 `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Amount        float64                `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TradeDao) Reset() {
	*x = TradeDao{}
	mi := &file_trade_dao_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TradeDao) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TradeDao) ProtoMessage() {}

func (x *TradeDao) ProtoReflect() protoreflect.Message {
	mi := &file_trade_dao_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TradeDao.ProtoReflect.Descriptor instead.
func (*TradeDao) Descriptor() ([]byte, []int) {
	return file_trade_dao_proto_rawDescGZIP(), []int{0}
}

func (x *TradeDao) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *TradeDao) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

func (x *TradeDao) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *TradeDao) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *TradeDao) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

var File_trade_dao_proto protoreflect.FileDescriptor

const file_trade_dao_proto_rawDesc = "" +
	"\n" +
	"\x0ftrade_dao.proto\x12\x04main\"z\n" +
	"\bTradeDao\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12\x12\n" +
	"\x04side\x18\x02 \x01(\tR\x04side\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x01R\x06amountB\tZ\a./;mainb\x06proto3"

var (
	file_trade_dao_proto_rawDescOnce sync.Once
	file_trade_dao_proto_rawDescData []byte
)

func file_trade_dao_proto_rawDescGZIP() []byte {
	file_trade_dao_proto_rawDescOnce.Do(func() {
		file_trade_dao_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_trade_dao_proto_rawDesc), len(file_trade_dao_proto_rawDesc)))
	})
	return file_trade_dao_proto_rawDescData
}

var file_trade_dao_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_trade_dao_proto_goTypes = []any{
	(*TradeDao)(nil), // 0: main.TradeDao
}
var file_trade_dao_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_trade_dao_proto_init() }
func file_trade_dao_proto_init() {
	if File_trade_dao_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_trade_dao_proto_rawDesc), len(file_trade_dao_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_trade_dao_proto_goTypes,
		DependencyIndexes: file_trade_dao_proto_depIdxs,
		MessageInfos:      file_trade_dao_proto_msgTypes,
	}.Build()
	File_trade_dao_proto = out.File
	file_trade_dao_proto_goTypes = nil
	file_trade_dao_proto_depIdxs = nil
}
